
[project]
name = "cbuild"

[build]
language = "c" # "cpp"
standard = "c89" # "c99", "c11", "c17", "c++98", "c++11", "c++14", "c++17", "c++20"
compiler = "gcc" # default = "gcc" | "clang", "msvc"
type = "bin" # default = "bin" | "lib", "dylib"
target = "x86_64-windows-msvc"
mode = "debug" # default = "debug" | "release"
compile_flags = ["-Wall", "-Wextra", "-Werror", "-pedantic"]
link_flags = ["lm"]
use_libc = true # default = "true" | "false"

[libraries]
core = "1.0.0"
